"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, ArrowRight, Building2, Check, FileDown, ImageUp, Mail, Printer, Save, Search, Share2, ShieldCheck, Trash2 } from "lucide-react";
import Image from "next/image";
import { type ChangeEvent, type CSSProperties, useEffect, useMemo, useRef, useState } from "react";
import { type FieldErrors, type UseFormRegister, useForm, useWatch } from "react-hook-form";
import { z } from "zod";
import { insurerProfiles } from "@/lib/catalog";
import { createPdfBlob, downloadPdf } from "@/lib/downloadPdf";

const schema=z.object({
  insurer:z.string().min(2,"Wybierz ubezpieczyciela"),
  vehicleType:z.enum(["samochod","jednoslad"]),year:z.string().min(4,"Wybierz rok produkcji"),make:z.string().min(2,"Wpisz markę"),model:z.string().min(1,"Wpisz model"),registration:z.string().min(4,"Wpisz numer rejestracyjny"),
  firstName:z.string().min(2,"Wpisz imię"),lastName:z.string().min(2,"Wpisz nazwisko"),postalCode:z.string().regex(/^\d{2}-\d{3}$/,"Format: 00-000"),city:z.string().min(2,"Wpisz miejscowość"),street:z.string().min(2,"Wpisz ulicę"),houseNumber:z.string().min(1,"Wpisz numer domu"),apartmentNumber:z.string().optional(),phone:z.string().min(7,"Wpisz numer telefonu"),
  policyEndDate:z.string().min(1,"Wybierz datę"),reason:z.enum(["art28","art28a","art31"]),policy:z.string().min(3,"Wpisz numer polisy"),insurerAddress:z.string().min(5,"Wpisz adres ubezpieczyciela"),insurerEmail:z.email("Wpisz poprawny e-mail ubezpieczyciela"),email:z.union([z.literal(""),z.email("Wpisz poprawny e-mail")]),privacy:z.boolean().refine(Boolean,"Akceptacja jest wymagana"),
});
type FormData=z.infer<typeof schema>;
type Register=UseFormRegister<FormData>;type Errors=FieldErrors<FormData>;

const defaults:Partial<FormData>={vehicleType:"samochod",reason:"art28",email:"",privacy:false};
const reasonLabels={art28:"Wypowiedzenie na koniec okresu ubezpieczenia — art. 28",art28a:"Polisa przedłużyła się automatycznie, a mam już inne OC — art. 28a",art31:"Pojazd został kupiony wraz z polisą — art. 31"} as const;
const years=Array.from({length:40},(_,index)=>String(new Date().getFullYear()-index));
const steps=["Ubezpieczyciel","Pojazd","Właściciel","Polisa","Podpis i podgląd"];
const draftKey="oc-documenty-wypowiedzenie-draft";

export function GeneratorForm(){
  const[step,setStep]=useState(1);const[submitted,setSubmitted]=useState(false);const[signature,setSignature]=useState("");const[signatureError,setSignatureError]=useState("");const[sendStatus,setSendStatus]=useState("");const draftReady=useRef(false);const draftStatus="Zapisano lokalnie";
  const{register,trigger,getValues,setValue,reset,control,formState:{errors}}=useForm<FormData>({resolver:zodResolver(schema),mode:"onBlur",defaultValues:defaults});
  const draftValues=useWatch({control});
  const insurer=draftValues.insurer;
  const data=getValues();
  const progress=Math.round(((step-1)/(steps.length-1))*100);
  const stepFields:Record<number,(keyof FormData)[]>={1:["insurer"],2:["vehicleType","year","make","model","registration"],3:["firstName","lastName","postalCode","city","street","houseNumber","phone"],4:["policyEndDate","reason","policy","insurerAddress","insurerEmail","email","privacy"]};

  useEffect(()=>{
    try{const saved=sessionStorage.getItem(draftKey);if(saved)reset({...defaults,...JSON.parse(saved),privacy:false});}catch{sessionStorage.removeItem(draftKey);}finally{draftReady.current=true;}
  },[reset]);
  useEffect(()=>{if(!draftReady.current)return;const draft={...draftValues,privacy:false};sessionStorage.setItem(draftKey,JSON.stringify(draft));},[draftValues]);

  async function next(){const valid=await trigger(stepFields[step]);if(valid)setStep((current)=>Math.min(current+1,steps.length));}
  function chooseInsurer(name:string){setValue("insurer",name,{shouldValidate:true,shouldDirty:true});}
  function addSignature(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setSignatureError("Wybierz zdjęcie JPG, PNG lub WEBP.");return;}if(file.size>5*1024*1024){setSignatureError("Zdjęcie może mieć maksymalnie 5 MB.");return;}const reader=new FileReader();reader.onload=()=>{setSignature(String(reader.result));setSignatureError("");};reader.readAsDataURL(file);}
  function createDocument(){if(!signature){setSignatureError("Dodaj zdjęcie podpisu przed utworzeniem dokumentu.");return;}sessionStorage.removeItem(draftKey);setSubmitted(true);}
  function sendEmail(){const current=getValues();const subject=encodeURIComponent(`Wypowiedzenie umowy OC — polisa ${current.policy}`);const body=encodeURIComponent(`Dzień dobry,\n\nw załączeniu przesyłam podpisane wypowiedzenie umowy OC pojazdu ${current.make} ${current.model}, nr rej. ${current.registration}.\n\nProszę o potwierdzenie otrzymania dokumentu.\n\n${current.firstName} ${current.lastName}`);window.location.href=`mailto:${current.insurerEmail}?subject=${subject}&body=${body}${current.email?`&cc=${encodeURIComponent(current.email)}`:""}`;setSendStatus("Otworzono pocztę. Dołącz zapisany plik PDF przed wysłaniem.");}
  async function share(){if(!navigator.share){setSendStatus("Udostępnianie systemowe nie jest dostępne. Pobierz PDF i wyślij go e-mailem.");return;}try{const blob=await createPdfBlob("oc-document");const file=new File([blob],"wypowiedzenie-oc.pdf",{type:"application/pdf"});if(!navigator.canShare?.({files:[file]})){setSendStatus("To urządzenie nie obsługuje udostępniania plików. Pobierz PDF i wyślij go e-mailem.");return;}await navigator.share({title:"Wypowiedzenie umowy OC",text:`Podpisane wypowiedzenie OC — polisa ${getValues("policy")}.`,files:[file]});setSendStatus("Plik PDF został przekazany do wybranej aplikacji.");}catch{setSendStatus("Udostępnianie zostało anulowane.");}}

  if(submitted){const current=getValues();return <section className="generatedOc"><div className="successSummary"><Check/><span className="premiumPill">Dokument gotowy</span><h2>Wypowiedzenie OC zostało przygotowane</h2><p>Sprawdź podgląd, pobierz PDF lub przekaż go do {current.insurer}.</p></div><OcDocument data={current} signature={signature}/><div className="documentActions"><button className="button buttonPrimary" onClick={()=>downloadPdf("oc-document","wypowiedzenie-oc.pdf")}><FileDown/> Pobierz PDF</button><button className="button buttonOutline" onClick={()=>window.print()}><Printer/> Drukuj</button><button className="button buttonOutline" onClick={share}><Share2/> Udostępnij PDF</button></div><section className="sendToParty ocSend"><h4>Wyślij do {current.insurer}</h4><p>Po otwarciu poczty dołącz zapisany dokument PDF.</p><label>Adres e-mail ubezpieczyciela<input type="email" value={current.insurerEmail} readOnly/></label><button className="button buttonPrimary" onClick={sendEmail}><Mail/> Przygotuj e-mail</button>{sendStatus&&<small role="status">{sendStatus}</small>}</section></section>}

  return <div className="generatorShell enterpriseGenerator"><header className="generatorProgressHeader"><div><span>Postęp dokumentu</span><strong>{progress}%</strong></div><div className="progressTrack"><i style={{width:`${progress}%`}}/></div><small><Save/> {draftStatus}</small></header><ol className="stepper generatorStepperFive">{steps.map((label,index)=><li className={step>=index+1?"active":""} aria-current={step===index+1?"step":undefined} key={label}><b>{step>index+1?<Check/>:index+1}</b><span>{label}</span></li>)}</ol><div className="generatorBody"><section className="formPanel"><div className="formHeading"><span>Krok {step} z {steps.length}</span><h2>{step===1?"Wybierz ubezpieczyciela":step===2?"Dane pojazdu":step===3?"Dane właściciela":step===4?"Dane polisy":"Sprawdź i podpisz"}</h2>{step===1&&<p>Wybierz firmę, z której polisy rezygnujesz.</p>}</div>{step===1&&<InsurerStep selected={insurer} choose={chooseInsurer} error={errors.insurer?.message}/>} {step===2&&<VehicleStep register={register} errors={errors}/>} {step===3&&<OwnerStep register={register} errors={errors}/>} {step===4&&<PolicyStep register={register} errors={errors} insurer={insurer}/>} {step===5&&<ReviewStep data={data} signature={signature} signatureError={signatureError} addSignature={addSignature} removeSignature={()=>setSignature("")}/>}<div className="formActions">{step>1&&<button className="button buttonOutline" onClick={()=>setStep((current)=>current-1)}><ArrowLeft/> Wstecz</button>}<button className="button buttonPrimary" onClick={step===5?createDocument:next}>{step===5?"Podpisz i utwórz":"Dalej"}<ArrowRight/></button></div></section><aside className="securityCard premiumSecurity"><div className="progressRing" style={{"--progress":`${progress*3.6}deg`} as CSSProperties}><span>{progress}%</span></div><h3>Twój dokument</h3><p>{insurer?`Wypowiedzenie OC — ${insurer}`:"Najpierw wybierz ubezpieczyciela."}</p><ul><li><Check/> Automatyczny zapis sesji</li><li><Check/> Walidacja wymaganych pól</li><li><Check/> Podpis zdjęciem</li><li><Check/> PDF, druk i udostępnianie</li></ul><small><ShieldCheck/> Dane nie są wysyłane automatycznie</small></aside></div></div>
}

function InsurerStep({selected,choose,error}:{selected?:string;choose:(name:string)=>void;error?:string}){const[query,setQuery]=useState("");const filtered=useMemo(()=>insurerProfiles.filter((item)=>item.name.toLocaleLowerCase("pl").includes(query.toLocaleLowerCase("pl"))),[query]);return <div className="insurerStep"><label className="insurerSearch"><Search/><span className="srOnly">Szukaj ubezpieczyciela</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Wpisz nazwę firmy..."/></label><div className="insurerSelectGrid">{filtered.map((item)=><button type="button" className={selected===item.name?"selected":""} onClick={()=>choose(item.name)} key={item.slug}><span>{item.name.slice(0,3)}</span><b>{item.name}</b>{selected===item.name&&<Check/>}</button>)}</div>{!filtered.length&&<div className="insurerEmpty"><Building2/><p>Nie znaleziono firmy. Sprawdź nazwę lub wybierz ją później w polu danych polisy.</p></div>}{error&&<small className="uploadError" role="alert">{error}</small>}</div>}
function ErrorText({message}:{message?:string}){return message?<small role="alert">{message}</small>:null}
function VehicleStep({register,errors}:{register:Register;errors:Errors}){return <div className="formGrid detailedForm"><fieldset className="wide choiceGroup"><legend>Rodzaj pojazdu</legend><label><input type="radio" value="samochod" {...register("vehicleType")}/> Samochód</label><label><input type="radio" value="jednoslad" {...register("vehicleType")}/> Motocykl / jednoślad</label></fieldset><label>Rok produkcji<select {...register("year")}><option value="">Wybierz rok</option>{years.map((year)=><option key={year}>{year}</option>)}</select><ErrorText message={errors.year?.message}/></label><label>Marka<input {...register("make")} placeholder="np. Volkswagen"/><ErrorText message={errors.make?.message}/></label><label>Model<input {...register("model")} placeholder="np. Passat"/><ErrorText message={errors.model?.message}/></label><label>Numer rejestracyjny<input {...register("registration")} placeholder="WA 12345"/><ErrorText message={errors.registration?.message}/></label></div>}
function OwnerStep({register,errors}:{register:Register;errors:Errors}){return <div className="formGrid detailedForm"><label>Imię<input {...register("firstName")} autoComplete="given-name"/><ErrorText message={errors.firstName?.message}/></label><label>Nazwisko<input {...register("lastName")} autoComplete="family-name"/><ErrorText message={errors.lastName?.message}/></label><label>Kod pocztowy<input {...register("postalCode")} placeholder="00-000" autoComplete="postal-code"/><ErrorText message={errors.postalCode?.message}/></label><label>Miejscowość<input {...register("city")} autoComplete="address-level2"/><ErrorText message={errors.city?.message}/></label><label className="wide">Ulica<input {...register("street")} autoComplete="address-line1"/><ErrorText message={errors.street?.message}/></label><label>Numer domu<input {...register("houseNumber")}/><ErrorText message={errors.houseNumber?.message}/></label><label>Numer mieszkania<input {...register("apartmentNumber")}/></label><label className="wide">Numer telefonu<input {...register("phone")} type="tel" placeholder="+48 500 123 456" autoComplete="tel"/><ErrorText message={errors.phone?.message}/></label></div>}
function PolicyStep({register,errors,insurer}:{register:Register;errors:Errors;insurer?:string}){return <div className="formGrid detailedForm"><div className="wide selectedInsurer"><span>{insurer?.slice(0,3)}</span><div><small>Wybrany ubezpieczyciel</small><strong>{insurer}</strong></div></div><label className="wide">Kiedy kończy się polisa?<input {...register("policyEndDate")} type="date"/><ErrorText message={errors.policyEndDate?.message}/></label><fieldset className="wide reasonGroup"><legend>Powód wypowiedzenia OC</legend>{Object.entries(reasonLabels).map(([value,label])=><label key={value}><input type="radio" value={value} {...register("reason")}/><span>{label}</span></label>)}</fieldset><label>Numer polisy<input {...register("policy")}/><ErrorText message={errors.policy?.message}/></label><label>Twój e-mail do kopii (opcjonalnie)<input {...register("email")} type="email" placeholder="twoj@mail.com"/><ErrorText message={errors.email?.message}/></label><label className="wide">Adres ubezpieczyciela<input {...register("insurerAddress")} placeholder="Ulica, kod pocztowy, miejscowość"/><ErrorText message={errors.insurerAddress?.message}/></label><label className="wide">E-mail ubezpieczyciela<input {...register("insurerEmail")} type="email" placeholder="adres do wysyłki dokumentów"/><ErrorText message={errors.insurerEmail?.message}/></label><p className="wide legalHint">Sprawdź adres i akceptowany kanał wysyłki na oficjalnej stronie firmy. Wypowiedzenie z art. 28 należy przekazać najpóźniej dzień przed końcem okresu ubezpieczenia.</p><label className="wide consent"><input type="checkbox" {...register("privacy")}/><span>Akceptuję <a href="/polityka-prywatnosci" target="_blank" rel="noopener noreferrer">politykę prywatności</a> i <a href="/regulamin" target="_blank" rel="noopener noreferrer">regulamin serwisu</a>.</span><ErrorText message={errors.privacy?.message}/></label></div>}
function ReviewStep({data,signature,signatureError,addSignature,removeSignature}:{data:Partial<FormData>;signature:string;signatureError:string;addSignature:(event:ChangeEvent<HTMLInputElement>)=>void;removeSignature:()=>void}){return <><div className="summary liveSummary enterpriseSummary"><span className="summaryBadge">Podgląd danych</span><div><p><small>Ubezpieczyciel</small><strong>{data.insurer}</strong></p><p><small>Ubezpieczający</small><strong>{data.firstName} {data.lastName}</strong><br/>{data.street} {data.houseNumber}{data.apartmentNumber?`/${data.apartmentNumber}`:""}, {data.postalCode} {data.city}</p><p><small>Pojazd i polisa</small><strong>{data.make} {data.model} ({data.year})</strong><br/>{data.registration} · {data.policy}</p></div><p>{data.reason?reasonLabels[data.reason]:""}</p></div><section className="signatureUpload"><h3>Podpis ubezpieczającego</h3><p>Zrób zdjęcie podpisu na białej kartce lub wybierz plik.</p>{signature?<div className="signaturePreview"><Image src={signature} alt="Podgląd podpisu" width={420} height={160} unoptimized/><button type="button" onClick={removeSignature}><Trash2/> Usuń</button></div>:<label className="uploadArea"><ImageUp/><strong>Dodaj zdjęcie podpisu</strong><span>JPG, PNG lub WEBP · maksymalnie 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={addSignature}/></label>}{signatureError&&<small className="uploadError" role="alert">{signatureError}</small>}</section></>}
function OcDocument({data,signature}:{data:FormData;signature:string}){return <article id="oc-document" className="ocPrintDocument"><header><strong><i>OC.</i>Documenty.pl</strong><span>Dokument wygenerowany online</span></header><p className="documentDate">{data.city}, dnia ____________________</p><div className="ocParties"><section><h3>Dane ubezpieczającego</h3><p><b>{data.firstName} {data.lastName}</b><br/>{data.street} {data.houseNumber}{data.apartmentNumber?`/${data.apartmentNumber}`:""}<br/>{data.postalCode} {data.city}<br/>{data.phone}</p></section><section><h3>Dane ubezpieczyciela</h3><p><b>{data.insurer}</b><br/>{data.insurerAddress}<br/>{data.insurerEmail}</p></section></div><section><h3>Dane polisy i pojazdu</h3><p>Numer polisy: <b>{data.policy}</b><br/>Pojazd: {data.make} {data.model}, rok {data.year}<br/>Numer rejestracyjny: {data.registration}<br/>Koniec polisy: {data.policyEndDate}</p></section><h1>WYPOWIEDZENIE UMOWY UBEZPIECZENIA OC</h1><p>Niniejszym wypowiadam umowę obowiązkowego ubezpieczenia odpowiedzialności cywilnej posiadaczy pojazdów mechanicznych dotyczącą wskazanego powyżej pojazdu.</p><p><b>Podstawa wypowiedzenia:</b> {reasonLabels[data.reason]}.</p><p>Proszę o potwierdzenie przyjęcia wypowiedzenia oraz przekazanie informacji o dacie rozwiązania umowy.</p><div className="ocSignature"><Image src={signature} alt="Podpis ubezpieczającego" width={300} height={100} unoptimized/><span>{data.firstName} {data.lastName} — podpis</span></div></article>}
