"use client";

import { ArrowLeft, ArrowRight, Check, FileDown, ImageUp, Mail, Save, Share2, Trash2 } from "lucide-react";
import Image from "next/image";
import { ChangeEvent, useState } from "react";
import { createPdfBlob, downloadPdf } from "@/lib/downloadPdf";

interface Field { name: string; label: string; placeholder: string; type?: "text"|"date"|"time"|"email"|"tel"; wide?: boolean }
interface Group { title: string; fields: Field[] }

const groups:Group[]=[
  {title:"Dane sprawcy",fields:[{name:"driverName",label:"Imię i nazwisko",placeholder:"Jan Kowalski"},{name:"driverAddress",label:"Adres zamieszkania",placeholder:"ul. Przykładowa 10",wide:true},{name:"driverPhone",label:"Numer telefonu",placeholder:"600 000 000",type:"tel"},{name:"driverLicense",label:"Numer prawa jazdy",placeholder:"ABC 123456"}]},
  {title:"Pojazd i polisa",fields:[{name:"vehicle",label:"Marka i model",placeholder:"Volkswagen Passat"},{name:"registration",label:"Numer rejestracyjny",placeholder:"WA 12345"},{name:"policy",label:"Numer polisy OC",placeholder:"1234567890"},{name:"insurer",label:"Ubezpieczyciel",placeholder:"Nazwa firmy"}]},
  {title:"Druga strona",fields:[{name:"otherName",label:"Imię i nazwisko poszkodowanego",placeholder:"Anna Nowak",wide:true},{name:"otherEmail",label:"Adres e-mail",placeholder:"anna@example.pl",type:"email"},{name:"otherPhone",label:"Numer telefonu",placeholder:"500 000 000",type:"tel"},{name:"otherVehicle",label:"Pojazd drugiej strony",placeholder:"Toyota Corolla"},{name:"otherRegistration",label:"Numer rejestracyjny",placeholder:"KR 54321"}]},
  {title:"Zdarzenie i podpis",fields:[{name:"eventDate",label:"Data zdarzenia",placeholder:"",type:"date"},{name:"eventTime",label:"Godzina",placeholder:"",type:"time"},{name:"eventPlace",label:"Miejsce zdarzenia",placeholder:"Warszawa",wide:true},{name:"description",label:"Opis przebiegu zdarzenia",placeholder:"Opisz przebieg kolizji...",wide:true}]},
];

export function CollisionForm(){
  const[step,setStep]=useState(0);
  const[done,setDone]=useState(false);
  const[values,setValues]=useState<Record<string,string>>({});
  const[errors,setErrors]=useState<Record<string,string>>({});
  const[signature,setSignature]=useState("");
  const[signatureError,setSignatureError]=useState("");
  const[recipientEmail,setRecipientEmail]=useState("");
  const[shareMessage,setShareMessage]=useState("");

  function update(name:string,value:string){setValues((current)=>({...current,[name]:value}));setErrors((current)=>({...current,[name]:""}));}
  function next(){const missing=Object.fromEntries(groups[step].fields.filter((field)=>!values[field.name]?.trim()).map((field)=>[field.name,"To pole jest wymagane."]));if(Object.keys(missing).length){setErrors(missing);return;}setStep((current)=>current+1);}
  function addSignature(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setSignatureError("Wybierz zdjęcie JPG, PNG lub WEBP.");return;}if(file.size>5*1024*1024){setSignatureError("Zdjęcie może mieć maksymalnie 5 MB.");return;}const reader=new FileReader();reader.onload=()=>{setSignature(String(reader.result));setSignatureError("");};reader.readAsDataURL(file);}
  function finish(){const missing=Object.fromEntries(groups[step].fields.filter((field)=>!values[field.name]?.trim()).map((field)=>[field.name,"To pole jest wymagane."]));if(Object.keys(missing).length){setErrors(missing);return;}if(!signature){setSignatureError("Dodaj zdjęcie podpisu, aby utworzyć dokument.");return;}setRecipientEmail(values.otherEmail??"");setDone(true);}
  function sendEmail(){if(!/^\S+@\S+\.\S+$/.test(recipientEmail)){setShareMessage("Wpisz poprawny adres e-mail drugiej strony.");return;}const subject=encodeURIComponent("Oświadczenie sprawcy kolizji drogowej");const body=encodeURIComponent("Dzień dobry,\n\nprzesyłam podpisane oświadczenie dotyczące kolizji drogowej. Dokument należy dołączyć w aplikacji pocztowej po zapisaniu go jako PDF.\n\nPozdrawiam");window.location.href=`mailto:${recipientEmail}?subject=${subject}&body=${body}`;setShareMessage("Otworzono aplikację pocztową. Dołącz zapisany dokument PDF przed wysłaniem.");}
  async function shareDocument(){if(!navigator.share){setShareMessage("Udostępnianie systemowe nie jest dostępne. Pobierz PDF i wyślij go e-mailem.");return;}try{const blob=await createPdfBlob(".printDocument");const file=new File([blob],"oswiadczenie-sprawcy.pdf",{type:"application/pdf"});if(!navigator.canShare?.({files:[file]})){setShareMessage("To urządzenie nie obsługuje udostępniania plików. Pobierz PDF i wyślij go e-mailem.");return;}await navigator.share({title:"Oświadczenie sprawcy kolizji",text:"Podpisane oświadczenie sprawcy kolizji drogowej.",files:[file]});setShareMessage("Plik PDF został przekazany do wybranej aplikacji.");}catch{setShareMessage("Udostępnianie zostało anulowane.");}}

  if(done)return <div className="collisionSuccess"><div className="successSummary"><Check/><h3>Oświadczenie jest podpisane</h3><p>Zapisz dokument jako PDF, a następnie przekaż go drugiej stronie.</p></div><PrintDocument values={values} signature={signature}/><div className="deliveryActions"><button className="button buttonPrimary" onClick={()=>downloadPdf(".printDocument","oswiadczenie-sprawcy.pdf")}><FileDown/> Pobierz PDF</button><button className="button buttonOutline" onClick={shareDocument}><Share2/> Udostępnij PDF</button></div><section className="sendToParty"><h4>Wyślij drugiej stronie</h4><p>Po otwarciu poczty dołącz zapisany wcześniej plik PDF.</p><label>Adres e-mail poszkodowanego<input type="email" value={recipientEmail} onChange={(event)=>setRecipientEmail(event.target.value)} placeholder="email@przyklad.pl" autoComplete="email"/></label><button className="button buttonPrimary" onClick={sendEmail}><Mail/> Przygotuj e-mail</button>{shareMessage&&<small role="status">{shareMessage}</small>}</section></div>;
  const group=groups[step];
  return <div className="collisionForm"><header className="toolProgress"><div><span>Postęp oświadczenia</span><strong>{Math.round(step/(groups.length-1)*100)}%</strong></div><i><b style={{width:`${step/(groups.length-1)*100}%`}}/></i><small><Save/> Dane pozostają na tym urządzeniu</small></header><ol>{groups.map((item,index)=><li className={index<=step?"active":""} key={item.title}><b>{index+1}</b><span>{item.title}</span></li>)}</ol><div className="formNotice">Wypełnij wszystkie pola. Dane zostaną umieszczone w gotowym dokumencie.</div><h3>{group.title}</h3><div className="collisionFieldGrid">{group.fields.map((field)=><label className={field.wide?"wide":""} key={field.name}>{field.label}<input type={field.type??"text"} value={values[field.name]??""} onChange={(event)=>update(field.name,event.target.value)} placeholder={field.placeholder} autoComplete="off"/>{errors[field.name]&&<small role="alert">{errors[field.name]}</small>}</label>)}</div>{step===groups.length-1&&<section className="signatureUpload"><h3>Podpis sprawcy</h3><p>Zrób zdjęcie podpisu na białej kartce lub wybierz zdjęcie z telefonu.</p>{signature?<div className="signaturePreview"><Image src={signature} alt="Podgląd podpisu sprawcy" width={420} height={160} unoptimized/><button type="button" onClick={()=>setSignature("")} aria-label="Usuń zdjęcie podpisu"><Trash2/> Usuń</button></div>:<label className="uploadArea"><ImageUp/><strong>Dodaj zdjęcie podpisu</strong><span>JPG, PNG lub WEBP · maksymalnie 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={addSignature}/></label>}{signatureError&&<small className="uploadError" role="alert">{signatureError}</small>}<small className="privacyNote">Zdjęcie jest przetwarzane wyłącznie na tym urządzeniu.</small></section>}<div className="formActions">{step>0&&<button className="button buttonOutline" onClick={()=>setStep(step-1)}><ArrowLeft/>Wstecz</button>}<button className="button buttonPrimary" onClick={step===groups.length-1?finish:next}>{step===groups.length-1?"Podpisz i utwórz":"Dalej"}<ArrowRight/></button></div></div>
}

function PrintDocument({values,signature}:{values:Record<string,string>;signature:string}){return <article className="printDocument collisionPrintDocument"><header className="printDocumentHeader"><div className="printBrand"><img src="/images/oc-brand.jpeg" alt="OC.Documenty.pl"/><div><strong><i>OC.</i>Documenty.pl</strong><span>Wzory dokumentów OC/AC online</span></div></div><div className="printMeta"><span>Wspólne oświadczenie</span><small>Dokument gotowy do wydruku</small></div></header><h1>OŚWIADCZENIE SPRAWCY KOLIZJI DROGOWEJ</h1><p className="printLead">Wypełnij czytelnie drukowanymi literami. Powyższy dokument możesz wydrukować, podpisać i przekazać drugiej stronie.</p><section><h2>1. Dane sprawcy</h2><p><b>{values.driverName}</b><br/>{values.driverAddress}<br/>tel. {values.driverPhone} · prawo jazdy: {values.driverLicense}</p></section><section><h2>2. Pojazd i polisa</h2><p><b>{values.vehicle}</b> · nr rej. {values.registration}<br/>Polisa OC {values.policy} · {values.insurer}</p></section><section><h2>3. Druga strona</h2><p><b>{values.otherName}</b> · tel. {values.otherPhone}<br/>{values.otherEmail}<br/>{values.otherVehicle} · nr rej. {values.otherRegistration}</p></section><section><h2>4. Okoliczności zdarzenia</h2><p>{values.eventDate}, godz. {values.eventTime} · {values.eventPlace}</p><p>{values.description}</p></section><p className="declaration">Oświadczam, że jestem sprawcą opisanego zdarzenia drogowego, a powyższe dane są zgodne z prawdą.</p><div className="documentSignature"><span>Podpis sprawcy</span><Image src={signature} alt="Podpis sprawcy" width={300} height={100} unoptimized/></div><footer className="printFooter"><div><strong>OC.Documenty.pl</strong><span>Profesjonalne wzory dokumentów</span></div><div>Wygenerowano przez OC.Documenty.pl</div><div>Strona 1 / 1</div></footer></article>}
