"use client";

import { ArrowLeft, ArrowRight, Check, FileDown, ImageUp, Printer, Trash2 } from "lucide-react";
import Image from "next/image";
import { ChangeEvent, useState } from "react";
import { downloadPdf } from "@/lib/downloadPdf";

const eventFields=["date","time","place","description","damage","injured"] as const;
const partyFields=["offenderName","offenderAddress","offenderPesel","offenderVehicle","offenderRegistration","offenderPolicy","participantName","participantAddress","participantPesel","participantVehicle","participantRegistration","participantPolicy"] as const;
const labels:Record<string,string>={date:"Data zdarzenia",time:"Godzina",place:"Miejsce zdarzenia",description:"Opis zdarzenia",damage:"Uszkodzenia pojazdów",injured:"Poszkodowani (jeśli występują)",offenderName:"Imię i nazwisko sprawcy",offenderAddress:"Adres sprawcy",offenderPesel:"PESEL sprawcy",offenderVehicle:"Marka i model pojazdu sprawcy",offenderRegistration:"Numer rejestracyjny sprawcy",offenderPolicy:"Numer polisy sprawcy",participantName:"Imię i nazwisko uczestnika",participantAddress:"Adres uczestnika",participantPesel:"PESEL uczestnika",participantVehicle:"Marka i model pojazdu uczestnika",participantRegistration:"Numer rejestracyjny uczestnika",participantPolicy:"Numer polisy uczestnika"};

export function JointStatementForm(){
  const[step,setStep]=useState(1);const[values,setValues]=useState<Record<string,string>>({});const[errors,setErrors]=useState<Record<string,string>>({});const[offenderSignature,setOffenderSignature]=useState("");const[participantSignature,setParticipantSignature]=useState("");const[done,setDone]=useState(false);const[signatureError,setSignatureError]=useState("");
  function update(name:string,value:string){setValues((current)=>({...current,[name]:value}));setErrors((current)=>({...current,[name]:""}));}
  function validate(names:readonly string[]){const missing=Object.fromEntries(names.filter((name)=>name!=="injured"&&!values[name]?.trim()).map((name)=>[name,"To pole jest wymagane."]));setErrors(missing);return Object.keys(missing).length===0;}
  function next(){if(step===1&&validate(eventFields))setStep(2);else if(step===2&&validate(partyFields))setStep(3);}
  function finish(){if(!offenderSignature||!participantSignature){setSignatureError("Dodaj czytelne podpisy obu stron.");return;}setDone(true);}
  function upload(setter:(value:string)=>void,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setSignatureError("Wybierz zdjęcie JPG, PNG lub WEBP do 5 MB.");return;}const reader=new FileReader();reader.onload=()=>{setter(String(reader.result));setSignatureError("");};reader.readAsDataURL(file);}
  if(done)return <section className="jointResult"><div className="successSummary"><Check/><h2>Wspólne oświadczenie jest gotowe</h2><p>Dokument zawiera dane oraz podpisy obu uczestników.</p></div><JointDocument values={values} offenderSignature={offenderSignature} participantSignature={participantSignature}/><div className="documentActions"><button className="button buttonPrimary" onClick={()=>downloadPdf(".jointDocument","wspolne-oswiadczenie.pdf")}><FileDown/> Pobierz PDF</button><button className="button buttonOutline" onClick={()=>window.print()}><Printer/> Drukuj</button></div></section>;
  return <div className="jointShell"><header className="toolProgress"><div><span>Postęp oświadczenia</span><strong>{Math.round((step-1)/2*100)}%</strong></div><i><b style={{width:`${(step-1)/2*100}%`}}/></i><small>Dane formularza są przetwarzane lokalnie</small></header><ol className="stepper jointStepper">{["Zdarzenie","Uczestnicy","Podpisy"].map((label,index)=><li className={step>=index+1?"active":""} key={label}><b>{step>index+1?<Check/>:index+1}</b><span>{label}</span></li>)}</ol><section className="jointBody"><div className="formHeading"><span>Krok {step} z 3</span><h2>{step===1?"Dane zdarzenia":step===2?"Dane obu uczestników":"Podpisy stron"}</h2></div>{step===1&&<Fields names={eventFields} values={values} errors={errors} update={update}/>} {step===2&&<div className="twoParties"><fieldset><legend>Sprawca zdarzenia</legend><Fields names={partyFields.slice(0,6)} values={values} errors={errors} update={update}/></fieldset><fieldset><legend>Drugi uczestnik</legend><Fields names={partyFields.slice(6)} values={values} errors={errors} update={update}/></fieldset></div>} {step===3&&<div className="twoSignatures"><Signature title="Podpis sprawcy" value={offenderSignature} change={(event)=>upload(setOffenderSignature,event)} remove={()=>setOffenderSignature("")}/><Signature title="Podpis uczestnika" value={participantSignature} change={(event)=>upload(setParticipantSignature,event)} remove={()=>setParticipantSignature("")}/>{signatureError&&<small className="uploadError" role="alert">{signatureError}</small>}</div>}<div className="formActions">{step>1&&<button className="button buttonOutline" onClick={()=>setStep(step-1)}><ArrowLeft/> Wstecz</button>}<button className="button buttonPrimary" onClick={step===3?finish:next}>{step===3?"Utwórz dokument":"Dalej"}<ArrowRight/></button></div></section></div>}

function Fields({names,values,errors,update}:{names:readonly string[];values:Record<string,string>;errors:Record<string,string>;update:(name:string,value:string)=>void}){return <div className="jointFields">{names.map((name)=><label className={["description","damage","injured","offenderAddress","participantAddress"].includes(name)?"wide":""} key={name}>{labels[name]}{["description","damage","injured"].includes(name)?<textarea value={values[name]??""} onChange={(event)=>update(name,event.target.value)} rows={3}/>:<input type={name==="date"?"date":name==="time"?"time":"text"} value={values[name]??""} onChange={(event)=>update(name,event.target.value)}/>} {errors[name]&&<small role="alert">{errors[name]}</small>}</label>)}</div>}
function Signature({title,value,change,remove}:{title:string;value:string;change:(event:ChangeEvent<HTMLInputElement>)=>void;remove:()=>void}){return <section className="signatureUpload"><h3>{title}</h3><p>Dodaj zdjęcie czytelnego podpisu na białej kartce.</p>{value?<div className="signaturePreview"><Image src={value} alt={title} width={420} height={160} unoptimized/><button onClick={remove}><Trash2/> Usuń</button></div>:<label className="uploadArea"><ImageUp/><strong>Dodaj zdjęcie podpisu</strong><span>JPG, PNG lub WEBP · do 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={change}/></label>}</section>}
function JointDocument({values,offenderSignature,participantSignature}:{values:Record<string,string>;offenderSignature:string;participantSignature:string}){return <article className="jointDocument"><header className="printDocumentHeader"><div className="printBrand"><img src="/images/oc-brand.jpeg" alt="OC.Documenty.pl"/><div><strong><i>OC.</i>Documenty.pl</strong><span>Wzory dokumentów OC/AC online</span></div></div><div className="printMeta"><span>Wspólne oświadczenie</span><small>Dokument gotowy do wydruku</small></div></header><h1>WSPÓLNE OŚWIADCZENIE<br/>O ZDARZENIU DROGOWYM</h1><p className="printLead">Wypełnij drukowanymi literami. Dokument możesz wydrukować i przekazać obu uczestnikom zdarzenia.</p><section><p><b>Data i godzina:</b> {values.date}, {values.time}</p><p><b>Miejsce zdarzenia:</b> {values.place}</p><p><b>Opis zdarzenia:</b><br/>{values.description}</p><p><b>Uszkodzenia pojazdów:</b><br/>{values.damage}</p><p><b>Poszkodowani:</b> {values.injured||"Brak"}</p></section><div className="jointParties"><Party title="Sprawca zdarzenia" prefix="offender" values={values}/><Party title="Uczestnik zdarzenia" prefix="participant" values={values}/></div><div className="jointSignatures"><div><Image src={offenderSignature} alt="Podpis sprawcy" width={280} height={90} unoptimized/><span>Czytelny podpis sprawcy zdarzenia</span></div><div><Image src={participantSignature} alt="Podpis uczestnika" width={280} height={90} unoptimized/><span>Czytelny podpis uczestnika zdarzenia</span></div></div><footer className="printFooter"><div><strong>OC.Documenty.pl</strong><span>Profesjonalne wzory dokumentów</span></div><div>Wygenerowano przez OC.Documenty.pl</div><div>Strona 1 / 1</div></footer></article>}
function Party({title,prefix,values}:{title:string;prefix:"offender"|"participant";values:Record<string,string>}){return <section><h2>{title}</h2><p><b>{values[`${prefix}Name`]}</b><br/>{values[`${prefix}Address`]}<br/>PESEL: {values[`${prefix}Pesel`]}</p><p>Pojazd: {values[`${prefix}Vehicle`]}<br/>Nr rejestracyjny: {values[`${prefix}Registration`]}<br/>Nr polisy: {values[`${prefix}Policy`]}</p></section>}
