import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

export const metadata:Metadata={title:"Polityka prywatności",description:"Informacje o prywatności i przetwarzaniu danych w serwisie OC.Documenty.pl."};

export default function PrivacyPage(){return <><Header/><main id="main-content" className="legalPage"><div className="container legalContent"><span className="eyebrow">Prywatność</span><h1>Polityka prywatności</h1><p className="legalLead">Ostatnia aktualizacja: 14 lipca 2026 r.</p><section><h2>1. Operator i kontakt</h2><p>OC.Documenty.pl jest częścią platformy Documenty.pl. Kontakt w sprawach prywatności: <a href="mailto:oc@documenty.pl">oc@documenty.pl</a>.</p><p><strong>Przed publicznym uruchomieniem serwisu operator musi uzupełnić tutaj pełną nazwę firmy, adres siedziby oraz dane rejestrowe.</strong></p></section><section><h2>2. Dane wpisywane w generatorach</h2><p>Dane formularzy oraz zdjęcia podpisów są przetwarzane lokalnie w przeglądarce użytkownika. Serwis nie zapisuje automatycznie treści wygenerowanych dokumentów na serwerze.</p></section><section><h2>3. Lokalna wersja robocza</h2><p>Generator wypowiedzenia może zapisywać tekstową wersję roboczą w pamięci sesji przeglądarki. Dane są usuwane po zakończeniu sesji lub utworzeniu dokumentu; zdjęcie podpisu nie jest zapisywane w wersji roboczej.</p></section><section><h2>4. Kontakt e-mail</h2><p>Skorzystanie z przygotowania wiadomości otwiera program pocztowy użytkownika. Wiadomość jest wysyłana dopiero po jej zatwierdzeniu przez użytkownika, zgodnie z zasadami dostawcy poczty.</p></section><section><h2>5. Dane techniczne</h2><p>Serwer może przetwarzać standardowe dane techniczne niezbędne do bezpieczeństwa i działania usługi, w tym adres IP, czas połączenia oraz informacje o przeglądarce. Szczegółowy okres przechowywania należy określić zgodnie z konfiguracją hostingu.</p></section><section><h2>6. Prawa użytkownika</h2><p>Użytkownik może zwrócić się o dostęp, sprostowanie, usunięcie lub ograniczenie przetwarzania danych oraz wnieść skargę do Prezesa Urzędu Ochrony Danych Osobowych, jeżeli dane są przetwarzane przez operatora.</p></section><section><h2>7. Pliki cookie</h2><p>Serwis korzysta wyłącznie z niezbędnych plików cookie, wymaganych do poprawnego działania strony. Wybór użytkownika dotyczący zgody na cookie jest zapamiętywany lokalnie w przeglądarce.</p></section></div></main><Footer/></>}



