import type { Metadata } from "next";
import { Check, Clock3, CloudDownload, FileText, ShieldCheck, Star, UsersRound } from "lucide-react";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { CollisionForm } from "@/features/collision/CollisionForm";

export const metadata: Metadata = { title: "Oświadczenie sprawcy kolizji", description: "Wypełnij oświadczenie sprawcy kolizji online i pobierz gotowy dokument." };

export default function CollisionPage(){return <><Header/><main id="main-content"><div className="container"><Breadcrumbs items={[{label:"Dokumenty",href:"/dokumenty"},{label:"Oświadczenie sprawcy kolizji"}]}/></div><section className="collisionHero"><div className="container collisionTop"><div><span className="eyebrow"><ShieldCheck/> Formularz po kolizji</span><h1>Oświadczenie<br/>sprawcy kolizji</h1><p>Wzór oświadczenia sprawcy kolizji drogowej. Wypełnij online, sprawdź dane i pobierz dokument.</p><div className="miniBenefits"><span><FileText/>Czytelny formularz</span><span><Clock3/>Wypełnij w kilka minut</span><span><ShieldCheck/>Dane przetwarzane lokalnie</span><span><CloudDownload/>PDF do pobrania</span></div><a className="button buttonPrimary buttonLarge" href="#formularz">Wypełnij oświadczenie</a></div><DocumentPreview compact/></div></section><section className="stats lightStats"><div className="container statsGrid"><div><UsersRound/><span><strong>Bez konta</strong><small>natychmiastowy dostęp</small></span></div><div><ShieldCheck/><span><strong>Lokalnie</strong><small>bez zapisu formularza</small></span></div><div><Star/><span><strong>Podpis zdjęciem</strong><small>JPG, PNG lub WEBP</small></span></div><div><ShieldCheck/><span><strong>PDF A4</strong><small>do pobrania i druku</small></span></div></div></section><section className="section" id="formularz"><div className="container collisionWorkspace"><div><h2>Podgląd dokumentu</h2><DocumentPreview/></div><div><h2>Wypełnij online</h2><CollisionForm/></div></div></section><section className="featureStrip"><div className="container">{[[Clock3,"Szybkie wypełnianie","Gotowy w kilka minut"],[FileText,"Dostępny online","Na komputerze i telefonie"],[CloudDownload,"Pobierz PDF","Gotowy do sprawdzenia"],[ShieldCheck,"Lokalne dane","Bez automatycznej wysyłki"]].map(([Icon,title,text])=><div key={String(title)}><Icon/><span><strong>{String(title)}</strong><small>{String(text)}</small></span></div>)}</div></section><section className="section soft"><div className="container"><div className="center"><h2>Jak to działa?</h2><p>Wypełnij oświadczenie w czterech prostych krokach.</p></div><div className="steps fourSteps">{["Wypełnij formularz","Sprawdź podgląd","Pobierz lub wyślij","Gotowe!"].map((title,index)=><article key={title}><b>{index+1}</b>{index===3?<Check/>:<FileText/>}<h3>{title}</h3><p>{index===0?"Podaj dane uczestników i pojazdów.":index===1?"Sprawdź poprawność informacji.":index===2?"Zapisz dokument jako PDF.":"Dokument jest gotowy do użycia."}</p></article>)}</div></div></section></main><Footer/></>}

function DocumentPreview({compact=false}:{compact?:boolean}){return <div className={`paperPreview ${compact?"compact":""}`}><header>OC.<strong>Documenty.pl</strong></header><h3>OŚWIADCZENIE SPRAWCY KOLIZJI DROGOWEJ</h3>{["1. DANE SPRAWCY KOLIZJI","2. DANE POJAZDU SPRAWCY","3. DANE ZDARZENIA"].map((section)=><div className="paperSection" key={section}><b>{section}</b><i></i><i></i><i></i></div>)}</div>}


